name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, hash, json, openssl, pcre, session, tokenizer, zlib
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install NPM dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create .env file
        run: |
          echo "APP_NAME=FVA" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "DEFAULT_URI=https://uat-identity.fva-vitaonyasany.mg" >> .env
          echo "MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0" >> .env
          echo "PORT=${{ secrets.SSH_PORT }}" >> .env
          echo "" >> .env
          echo "DATABASE_URL=mysql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_DATABASE }}" >> .env
          cat .env
          
      - name: Cleanup before deployment
        run: |
          rm -rf .git .github node_modules var

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          tar_tmp_path: false
          rm: false
          source: "."
          target: ${{ secrets.WORK_DIR }}
      - name: Run post-deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.WORK_DIR }}
            php bin/console doctrine:schema:update --dump-sql --force --env=prod
            php bin/console cache:clear --env=prod
            php bin/console assets:install public --env=prod
